Repository ena-isme/soso_cote_club, pull requests merged in 2025-08, with the labels that each got.

#4 [은정] Day1_1
  eunjung/day1_1.java
Labels: Java

#6 [지원] Day2
  jiwon/day2_1.cpp
  jiwon/day2_2.cpp
  jiwon/day2_3.cpp
Labels: C++

#12 [지원] Day3
  jiwon/day3_1.cpp
  jiwon/day3_2.cpp
  jiwon/day3_3.cpp
Labels: C++

#13 [연진] Day3_1
  yeonjin/day3_1.kt
Labels: Kotlin

#16 [은정] day3_1
  eunjung/day3_1.java
Labels: Java

#17 [지원] Day4
  jiwon/day4_1.cpp
Labels: C++
