Repository ena-isme/soso_cote_club, pull requests merged in 2025-09, with the labels that each got.

#20 [지원] Day5
  jiwon/day5_1.cpp
  jiwon/day5_2.cpp
Labels: C++

#25 [지원] Day6
  jiwon/day6_1.cpp
Labels: C++

#26 [명지] Day6
  myeongji/day6_1.kt
Labels: Kotlin

#27 [기중] Day6
  kijung/day6_1.java
  kijung/day6_2.java
  kijung/day6_3.java
Labels: Java

#30 [기중] Day7
  kijung/day7_1.java
  kijung/day7_3.java
Labels: Java

#31 [서연] Day8
  seoyeon/day8_1.cpp
  seoyeon/day8_knapsack_1.cpp
Labels: C++

#33 [은정] day8_1
  eunjung/day8_1.java
Labels: Java

#36 [명지] Day9
  myeongji/day9_1.kt
Labels: Kotlin
